### PR TITLE
Sections

### PR DESCRIPTION
**Pull request by sabanyelkenci**
Showcase and useful sections

### CODE REVIEW

**Review by erkamguresen — CHANGES_REQUESTED** [review]
Current branch is out of date. Need to merge or rebase (no books page).

looks of terrible in iphones (in mobile)

text is almost overflowed on right side (look the pictures)

Screenshot (87)
Screenshot (88)

If you need help just notify.

**Comment by erkamguresen** [comment]
@sabanyelkenci  now the main is merged branch is up to date but the previous part are gone. It is almost empty page now?

**Comment by sabanyelkenci** [comment]
> @sabanyelkenci now the main is merged branch is up to date but the previous part are gone. It is almost empty page now?

Hi @erkamguresen. We can review the code together this evening. I tried to use bootstrap but as you know I am not so experienced with bootstrap.

**Comment by IrinaSing** [comment]
Hi @sabanyelkenci there are some tutorials that help to make it clear about bootstrap

I mentioned them in your navbar PR

- https://youtu.be/1v_XcJsGtyA

- https://www.youtube.com/watch?v=4sosXZsdy-s

**Pull request closed without merging**
