### PR TITLE
Navbar menu

### PR DESCRIPTION
**Pull request by sabanyelkenci**

### CODE REVIEW

**Review by erkamguresen — CHANGES_REQUESTED** [review]
- this branch is out of date. Needs to rebase or merge. 
- mobile version does not show all links.
- logo is cut from horns, seems squizzed inside the bar
- "Readeer" text moves everywhere as the size of page changes including on the logo and under the logo...
- branch has merge conflics that must be solved

Screenshot (89)
Screenshot (90)
Screenshot (91)

**Comment by IrinaSing** [comment]
Hi @sabanyelkenci
I think problem may come because you put navbar ("nav") inside a fluid div. 
I think make sense to make "nav" first (it is fluid by default ) and then to put all the content inside including logo.
### Bootstrap example (html)
https://github.com/IrinaSing/irina-portfolio-githubAPI/blob/master/client/src/components/layout/navbar.js
### Example component
https://github.com/IrinaSing/irina-portfolio-githubAPI/blob/master/client/src/components/layout/navbar.js

**Comment by IrinaSing** [comment]
@sabanyelkenci a good video with step-by-step tutorial, navbar starts at 3:07, here is the link:
https://youtu.be/1v_XcJsGtyA?t=187

Also this tutorial there you can find navbar and showcase in timecodes.
https://www.youtube.com/watch?v=4sosXZsdy-s

**Comment by IrinaSing** [comment]
@sabanyelkenci 
icon with a white circle background in google drive folder
https://drive.google.com/file/d/12s4HQoUYON-7NEXV_JhGkenmatXjX7Wh/view

**Review by erkamguresen — APPROVED** [review]

**Review by Fatihayoz — APPROVED** [review]

**Pull request merged**
